---
queue-size: 10
sink-queue-size: 10
log-level: "info"
log-format: "console"
sources:
  - name: "radarr"
    type: "radarr"
    config:
      webhook_user: "radarr"
      webhook_pass: "radarr"
    sinks:
      - "log"
sinks:
  - name: "log"
    type: "log"
    config:
      level: "debug"