---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: ghcr.io/rtrox/informer-devel
    newTag: sha-9ef33b4-20230604004759
commonLabels:
  app.kubernetes.io/part-of: informer-devel
  k8s-app: informer-devel
