---
name: Handle Push to Main Branch
# https://dev.to/koddr/github-action-for-release-your-go-projects-as-fast-and-easily-as-possible-20a2
# https://github.com/orgs/community/discussions/25244
on:
  push:
    branches:
      - main

jobs:
  tests:
    uses: ./.github/workflows/tests.yaml

  build-and-push:
    needs: tests
    uses: ./.github/workflows/docker-image.yaml
    with:
      push: true
      suffix: -devel

  deploy_develop:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: update-image-tag
        run: |
          yq -i ".images |= map(select(.name == \"${{ needs.build-and-push.outputs.registry_image }}\").newTag=\"${{ needs.build-and-push.outputs.version }}\")" .github/ci/develop/kustomization.yaml

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "[CI][Dev] Update image tag to ${{ needs.build-and-push.outputs.version }}"
          committer: GitHub <noreply@github.com>
          title: "[CI][Dev] Update image tag to ${{ needs.build-and-push.outputs.version }}"
          body: |
            This PR was automatically created by GitHub Actions, and updates the image tag on the development deployment to ${{ needs.build-and-push.outputs.version }}.
          signoff: true
          delete-branch: true
          labels: ci
          reviewers: rtrox
          assignees: rtrox

      - name: Auto Merge Pull Request
        if: steps.cpr.outputs.pull-request-operation == 'created'
        run: gh pr merge --merge --auto "${{ steps.cpr.outputs.pull-request-number }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
